### ISSUE TITLE
Use Official Nest API

### ISSUE THREAD

**Issue by mutewinter** [jason0x43/jc-nest#12]
https://developer.nest.com/

**Comment by jason0x43** [comment]
I mostly finished a rewrite of the workflow this weekend that uses the official API this weekend. On the plus side, the API is better documented, and hopefully better supported and less flakey than the unofficial API. On the minus side, there's no fan control in the official API.

**Comment by gabrielrinaldi** [comment]
@jason0x43 where can I download it from?

**Comment by jason0x43** [comment]
I haven't posted it yet, but it will eventually be at jason0x43/alfred-nest.

**Comment by jason0x43** [comment]
The source, along with an initial release (pre-release, really), is [now up](https://github.com/jason0x43/alfred-nest/releases)
