### ISSUE TITLE
"nest nest" not showing Nest names

### ISSUE THREAD

**Issue by fdstevex** [jason0x43/jc-nest#14]
When picking the Nest thermostat to use, the "nest nest" command isn't showing the Nest name, just the ID.

![napkin 2 16-07-29 8 45 00 am](https://cloud.githubusercontent.com/assets/4220256/17248469/bcd489ee-5568-11e6-8de1-fb0a6abac939.png)

**Comment by jason0x43** [comment]
Could you give the newer version a try (at https://github.com/jason0x43/alfred-nest)? It uses the official Nest API and is a bit more up-to-date.

**Comment by fdstevex** [comment]
That worked for me.  Thanks!
