### ISSUE TITLE
Can't change temp or perform other actions

### ISSUE THREAD

**Issue by danieljimenez** [jason0x43/jc-nest#15]
For some reason the workflow stopped working. When I type "nest temp 78" for example, and press return, nothing happens, and the Alfred window doesn't dismiss 😢 .

Am I alone, or is anyone else seeing this?

**Comment by jason0x43** [comment]
This workflow uses the unofficial API and is no longer maintained, so you may want to give my [newer version](https://github.com/jason0x43/alfred-nest) a try.

**Comment by danieljimenez** [comment]
Thanks so much, sorry for the confusion!!
